---

- name: Install dependencies
  yum: 
    name: "{{ item }}"
    state: "installed"
  loop: "{{ yum_packages }}"

- name: ensure 'PasswordAuthentication yes' is present in '/etc/ssh/sshd_config'
  lineinfile: 
    path: "etc/ssh/sshd_config"
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
  notify: restartSSH
  